### ISSUE TITLE
Binary name conflict

### ISSUE THREAD

**Issue by grawlinson** [charmbracelet/melt#6]
While packaging this for the AUR, I noticed that if the binary is called `melt`, it conflicts with [`mlt`](https://www.mltframework.org/).

Does anyone have any suggestions for an alternate name? `melt-key` maybe?

**Comment by u0nel** [comment]
it's melt-bin already https://aur.archlinux.org/packages/melt-bin

**Comment by caarlos0** [comment]
yep, it is already on aur.

closing, thanks everyone :)

**Comment by dunxen** [comment]
Sorry to bring this up again, but running into the same issue having [`mlt`](https://launchpad.net/ubuntu/+search?text=melt) installed with apt :)
