### ISSUE TITLE
scoop install fails

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/melt#90]
PS C:\Users\drewr\scoop-charmbracelet> scoop install melt    
Couldn't find manifest for 'melt'.
![image](https://github.com/charmbracelet/melt/assets/11225574/bbcca97c-0682-4c0d-9263-e89b21ff1969)

**Comment by caarlos0** [comment]
need to add our bucket first:

```
scoop bucket add https://github.com/charmbracelet/scoop-bucket.git
```

fixed the docs, thanks for pointing this out!
